// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUqbbhQLqfrMiD8jPFYEoW0jTaXVnpsqk',
    appId: '1:24265147371:web:180950b9a0448f9c6a4fae',
    messagingSenderId: '24265147371',
    projectId: 'app-pokemon-73fee',
    authDomain: 'app-pokemon-73fee.firebaseapp.com',
    databaseURL: 'https://app-pokemon-73fee-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-73fee.appspot.com',
    measurementId: 'G-CY3ZL9EY60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYXZHQXVFlibgGaDwV5pfyPfla6V4uxC0',
    appId: '1:24265147371:android:bd74bae9e81abeaa6a4fae',
    messagingSenderId: '24265147371',
    projectId: 'app-pokemon-73fee',
    databaseURL: 'https://app-pokemon-73fee-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-73fee.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-e7WKa4ziIrX5JxWR4UQVZFyTh4v1ms',
    appId: '1:24265147371:web:59ad4cb68f08d5ce6a4fae',
    messagingSenderId: '24265147371',
    projectId: 'app-pokemon-73fee',
    authDomain: 'app-pokemon-73fee.firebaseapp.com',
    databaseURL: 'https://app-pokemon-73fee-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-73fee.appspot.com',
    measurementId: 'G-907B71Y0MS',
  );

}